import "./globals.css";
import Link from "next/link";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSearch } from '@fortawesome/free-solid-svg-icons';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { TheHeader } from './components/TheHeader';

export const metadata = {
  title: "Noah Furniture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-full bg-gray-200">
        <TheHeader />
        {children}
      </body>
    </html>
  );
}
